# -*- coding: utf-8 -*-
"""Copy of gravity_131.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjm6P5IvCF_7vNPCJm-tAkxrL_QeVb4P
"""

import pandas as pd

from google.colab import files
data = files.upload()

df = pd.read_csv('Main_Final.csv')

df.head()

df.columns

df.drop(['Unnamed: 0'],axis=1,inplace=True)

df.head()

df.dtypes

radius = df['Radius'].to_list()
mass = df['Mass'].to_list()
name = df['Star_Name'].tolist()
gravity =[]

#converting solar mass and radius into km & kg
def convert_to_si(radius,mass):
    for i in range(0,len(radius)-1):
        radius[i] = radius[i]*6.957e+8
        mass[i] = mass[i]*1.989e+30
        
convert_to_si(radius,mass)

def gravity_calculation(radius,mass):
    G = 6.674e-11
    for index in range(0,len(mass)):
        g= (mass[index]*G)/((radius[index])**2)
        gravity.append(g)
        
gravity_calculation(radius,mass)

df["Gravity"] = gravity
df

#df['Distance']=df['Distance'].apply(lambda x: x.replace('$', '').replace(',', '')).astype('float')
df.to_csv("star_with_gravity.csv")

df.dtypes

import plotly.express as px

radius.sort()
mass.sort()
gravity.sort()

fig = px.scatter(df,x="Radius", y="Mass", title="Relationship between Radius and Mass",hover_data=["Star_Name"]) 
fig.show()

fig = px.scatter(df,x="Radius", y="Gravity",title="Relationship between Radius and Gravity",hover_data=["Star_Name"]) 
fig.show()